### ISSUE TITLE
Generate wrong css order

### ISSUE THREAD

**Issue by zuibunan** [webpack-contrib/extract-text-webpack-plugin#171]
``` sass
 .selection:before {
    content: "";
    position: absolute;
    left: 8px;
    bottom: -10px;
    border: 10px solid rgba(0,0,0,0);
    border-top-color: gray;
    border-bottom-width: 0;
}
.selection:after {
    content: "";
    position: absolute;
    left: 8px;
    bottom: -10px;
    border: 10px solid rgba(0,0,0,0);
    border-top-color: white;
    border-bottom-width: 0;
    z-index:1;
}
```

to

``` css
.selection:before {
    border-top-color: gray
}

.selection:after,.selection:before {
    content: "";
    position: absolute;
    left: 8px;
    bottom: -10px;
    border: 10px solid transparent;
    border-bottom-width: 0
}

.selection:after {
    border-top-color: #fff;
    z-index: 1
}
```
