### ISSUE TITLE
Question: how to compile pseudo classes in the right way

### ISSUE THREAD

**Issue by antoniojunyor** [webpack-contrib/extract-text-webpack-plugin#442]
So ... I really don't know if I should make this issue here, in **sass-loader** ou **css-loader**.

When I wrote my SASS file I put:

```sass
*::before,
*::after
    box-sizing: inherit
```

but my generated CSS is like:
```css
*:after,
*:before {
    box-sizing: inherit;
}
```

What I should to to compile my pseudo elements in the right way (with two `::`)
