### ISSUE TITLE
Breaks with NamedModulesPlugin

### ISSUE THREAD

**Issue by cletusw** [webpack-contrib/extract-text-webpack-plugin#648]
`extract-text-webpack-plugin` breaks when combined with `webpack.NamedModulesPlugin`. It incorrectly outputs the result of extracting the CSS from the first bundle in all assets.

**main.css**
```css
body {
  background: blue;
}
```

**other.css**
```css
body {
  border: 10px solid yellow;
}
```

becomes

**main.built.css**
```css
body {
  background: blue;
}
```

**other.built.css**
```css
body {
  background: blue;
}
```

`node --version`: v8.5.0
`npm --version`: 5.5.1
`npm ls --depth=0`:
```
├── extract-text-webpack-plugin@3.0.1
├── raw-loader@0.5.1
└── webpack@3.7.1
```

EDIT: Minimal repro case: https://github.com/cletusw/extract-text-webpack-plugin-issue-648
