### ISSUE TITLE
"module.exports = (__webpack_require__(11))(81)" in css file

### ISSUE THREAD

**Issue by duan602728596** [webpack-contrib/extract-text-webpack-plugin#730]
Version: 4.0.0-beta.0

In the css file will appear like this: 
```css
._27UTc{margin-bottom:20px}
module.exports = (__webpack_require__(11))(81);._6DbbZ{overflow-x:hidden;overflow-y:auto;border-right:1px solid #e9e9e9;background-color:transparent}._3ORv7{display:inline-block;margin-right:8px;min-width:14px;vertical-align:-1px}
```

In the compiled css file will appear similar `module.exports = (__webpack_require __ (n)) (j);` such code.

**Comment by evilebottnawi** [comment]
@duan602728596 Can you upgrade to `webpack@4` stable and confirm what issue exists?

**Comment by hakan-andersson** [comment]
Try deleting node_modules and do a npm install, that did the trick for me.

**Comment by duan602728596** [comment]
@evilebottnawi 
I deleting node_modules and do a npm install, and try again in the development environment.
Sorry, I can not provide a minimal demo because I do not know where the problem is. If necessary, I can provide a relatively complete demo.

The code inside css is
```css
.src-modules-Form-Index-style__formGroup___27UTc50UxVSkeLi{margin-bottom:20px}
module.exports = (__webpack_require__(/*! dll-reference dll_812fb2874a3abb4da276 */ "dll-reference dll_812fb2874a3abb4da276"))("./node_modules/hoist-non-react-statics/index.js");.src-assembly-Sider-style__sider___6DbbZ1n6024aj7E{overflow-x:hidden;overflow-y:auto;border-right:1px solid #e9e9e9;background-color:transparent}
```
It does not show up when I do not use `DllPlugin` and `DllReferencePlugin`.
CSS is a framework style that does not show up when I comment out the loading style.

It does not show up when I try to build a simple demo based on the above question.
Or perhaps it is caused by multiple components.
